export const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "TICKER", uid: "tickerPair", sortable: true },
  { name: "EXCHANGE", uid: "exchange", sortable: true },
  { name: "QUANTITY", uid: "quantity", sortable: true },
  { name: "MARKET PRICE", uid: "market", sortable: true },
  { name: "NOMINAL VALUE", uid: "nominal", sortable: true },
];

export const statusOptions = [
  { name: "Open", uid: "active" },
  { name: "Closed", uid: "inactive" },
];

export const holdings = [
  {
    id: 1,
    tickerPair: "BTC-USD",
    exchange: "Coinbase",
    quantity: "0.5",
    market: "69000",
    nominal: "34500",
    status: "active",
  },
  {
    id: 2,
    tickerPair: "ETH-USD",
    exchange: "Binance",
    quantity: "2",
    market: "4000",
    nominal: "8000",
    status: "active",
  },
  {
    id: 3,
    tickerPair: "XRP-USD",
    exchange: "Kraken",
    quantity: "1000",
    market: "1.5",
    nominal: "1500",
    status: "inactive",
  },
  {
    id: 4,
    tickerPair: "LTC-USD",
    exchange: "Gemini",
    quantity: "10",
    market: "200",
    nominal: "2000",
    status: "active",
  },
  {
    id: 5,
    tickerPair: "ADA-USD",
    exchange: "Coinbase",
    quantity: "500",
    market: "2",
    nominal: "1000",
    status: "active",
  },
  {
    id: 6,
    tickerPair: "DOGE-USD",
    exchange: "Binance",
    quantity: "10000",
    market: "0.3",
    nominal: "3000",
    status: "inactive",
  },
  {
    id: 7,
    tickerPair: "DOT-USD",
    exchange: "Kraken",
    quantity: "80",
    market: "35",
    nominal: "2800",
    status: "active",
  },
  {
    id: 8,
    tickerPair: "SOL-USD",
    exchange: "Gemini",
    quantity: "20",
    market: "150",
    nominal: "3000",
    status: "active",
  },
  {
    id: 9,
    tickerPair: "UNI-USD",
    exchange: "Coinbase",
    quantity: "50",
    market: "25",
    nominal: "1250",
    status: "inactive",
  },
  {
    id: 10,
    tickerPair: "LINK-USD",
    exchange: "Binance",
    quantity: "100",
    market: "30",
    nominal: "3000",
    status: "active",
  },
  {
    id: 11,
    tickerPair: "BTC-EUR",
    exchange: "Coinbase",
    quantity: "0.4",
    market: "62000",
    nominal: "24800",
    status: "active",
  },
  {
    id: 12,
    tickerPair: "ETH-EUR",
    exchange: "Binance",
    quantity: "1.5",
    market: "3500",
    nominal: "5250",
    status: "active",
  },
  {
    id: 13,
    tickerPair: "XRP-EUR",
    exchange: "Kraken",
    quantity: "900",
    market: "1.2",
    nominal: "1080",
    status: "inactive",
  },
  {
    id: 14,
    tickerPair: "LTC-EUR",
    exchange: "Gemini",
    quantity: "8",
    market: "180",
    nominal: "1440",
    status: "active",
  },
  {
    id: 15,
    tickerPair: "ADA-EUR",
    exchange: "Coinbase",
    quantity: "400",
    market: "1.8",
    nominal: "720",
    status: "active",
  },
  {
    id: 16,
    tickerPair: "DOGE-EUR",
    exchange: "Binance",
    quantity: "9000",
    market: "0.25",
    nominal: "2250",
    status: "inactive",
  },
  {
    id: 17,
    tickerPair: "DOT-EUR",
    exchange: "Kraken",
    quantity: "70",
    market: "32",
    nominal: "2240",
    status: "active",
  },
  {
    id: 18,
    tickerPair: "SOL-EUR",
    exchange: "Gemini",
    quantity: "18",
    market: "140",
    nominal: "2520",
    status: "active",
  },
  {
    id: 19,
    tickerPair: "UNI-EUR",
    exchange: "Coinbase",
    quantity: "45",
    market: "23",
    nominal: "1035",
    status: "inactive",
  },
  {
    id: 20,
    tickerPair: "LINK-EUR",
    exchange: "Binance",
    quantity: "90",
    market: "28",
    nominal: "2520",
    status: "active",
  },
  {
    id: 21,
    tickerPair: "BTC-USD",
    exchange: "Coinbase",
    quantity: "0.45",
    market: "64000",
    nominal: "28800",
    status: "active",
  },
  {
    id: 22,
    tickerPair: "ETH-USD",
    exchange: "Binance",
    quantity: "1.8",
    market: "3700",
    nominal: "6660",
    status: "active",
  },
  {
    id: 23,
    tickerPair: "XRP-USD",
    exchange: "Kraken",
    quantity: "1100",
    market: "1.4",
    nominal: "1540",
    status: "inactive",
  },
  {
    id: 24,
    tickerPair: "LTC-USD",
    exchange: "Gemini",
    quantity: "9",
    market: "210",
    nominal: "1890",
    status: "active",
  },
  {
    id: 25,
    tickerPair: "ADA-USD",
    exchange: "Coinbase",
    quantity: "470",
    market: "2.2",
    nominal: "1034",
    status: "active",
  },
  {
    id: 26,
    tickerPair: "DOGE-USD",
    exchange: "Binance",
    quantity: "9500",
    market: "0.35",
    nominal: "3325",
    status: "inactive",
  },
  {
    id: 27,
    tickerPair: "DOT-USD",
    exchange: "Kraken",
    quantity: "75",
    market: "40",
    nominal: "3000",
    status: "active",
  },
  {
    id: 28,
    tickerPair: "SOL-USD",
    exchange: "Gemini",
    quantity: "17",
    market: "160",
    nominal: "2720",
    status: "active",
  },
  {
    id: 29,
    tickerPair: "UNI-USD",
    exchange: "Coinbase",
    quantity: "55",
    market: "28",
    nominal: "1540",
    status: "inactive",
  },
  {
    id: 30,
    tickerPair: "LINK-USD",
    exchange: "Binance",
    quantity: "95",
    market: "33",
    nominal: "3135",
    status: "active",
  },
  {
    id: 31,
    tickerPair: "BTC-EUR",
    exchange: "Coinbase",
    quantity: "0.42",
    market: "62000",
    nominal: "26040",
    status: "active",
  },
  {
    id: 32,
    tickerPair: "ETH-EUR",
    exchange: "Binance",
    quantity: "1.6",
    market: "3500",
    nominal: "5600",
    status: "active",
  },
  {
    id: 33,
    tickerPair: "XRP-EUR",
    exchange: "Kraken",
    quantity: "950",
    market: "1.2",
    nominal: "1140",
    status: "inactive",
  },
  {
    id: 34,
    tickerPair: "LTC-EUR",
    exchange: "Gemini",
    quantity: "7.5",
    market: "180",
    nominal: "1350",
    status: "active",
  },
  {
    id: 35,
    tickerPair: "ADA-EUR",
    exchange: "Coinbase",
    quantity: "430",
    market: "1.8",
    nominal: "774",
    status: "active",
  },
];
