const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "TICKER PAIR", uid: "tickerPair", sortable: true },
  { name: "EXCHANGE", uid: "exchange", sortable: true },
  { name: "POSITION SIZE", uid: "size", sortable: true },
  { name: "MARKET PRICE", uid: "market", sortable: true },
  { name: "NOMINAL VALUE", uid: "nominal", sortable: true },
  { name: "PNL", uid: "pnl", sortable: true },
  { name: "BREAK EVEN", uid: "breakEven", sortable: true },
];

const statusOptions = [
  { name: "Open", uid: "open" },
  { name: "Closed", uid: "closed" },
  { name: "Pending", uid: "pending" },
];

const trades = [
  {
    id: 1,
    tickerPair: "BTC-USD",
    exchange: "Coinbase",
    size: "34",
    market: "69000",
    nominal: "343949584",
    pnl: "+12%",
    breakEven: "64000",
    status: "open",
  },
  {
    id: 2,
    tickerPair: "ETH-USD",
    exchange: "Binance",
    size: "15",
    market: "4000",
    nominal: "60000",
    pnl: "+8%",
    breakEven: "3700",
    status: "open",
  },
  {
    id: 3,
    tickerPair: "XRP-USD",
    exchange: "Kraken",
    size: "1200",
    market: "1.5",
    nominal: "1800",
    pnl: "-5%",
    breakEven: "1.6",
    status: "pending",
  },
  {
    id: 4,
    tickerPair: "LTC-USD",
    exchange: "Gemini",
    size: "50",
    market: "200",
    nominal: "10000",
    pnl: "+3%",
    breakEven: "195",
    status: "closed",
  },
  {
    id: 5,
    tickerPair: "ADA-USD",
    exchange: "Coinbase",
    size: "500",
    market: "2",
    nominal: "1000",
    pnl: "+10%",
    breakEven: "1.8",
    status: "open",
  },
  {
    id: 6,
    tickerPair: "DOGE-USD",
    exchange: "Binance",
    size: "10000",
    market: "0.3",
    nominal: "3000",
    pnl: "+20%",
    breakEven: "0.25",
    status: "open",
  },
  {
    id: 7,
    tickerPair: "DOT-USD",
    exchange: "Kraken",
    size: "80",
    market: "35",
    nominal: "2800",
    pnl: "+15%",
    breakEven: "30",
    status: "pending",
  },
  {
    id: 8,
    tickerPair: "SOL-USD",
    exchange: "Gemini",
    size: "60",
    market: "150",
    nominal: "9000",
    pnl: "+5%",
    breakEven: "140",
    status: "closed",
  },
  {
    id: 9,
    tickerPair: "UNI-USD",
    exchange: "Coinbase",
    size: "100",
    market: "25",
    nominal: "2500",
    pnl: "-3%",
    breakEven: "26",
    status: "open",
  },
  {
    id: 10,
    tickerPair: "LINK-USD",
    exchange: "Binance",
    size: "200",
    market: "30",
    nominal: "6000",
    pnl: "+12%",
    breakEven: "27",
    status: "open",
  },
  {
    id: 11,
    tickerPair: "BTC-EUR",
    exchange: "Coinbase",
    size: "40",
    market: "62000",
    nominal: "2480000",
    pnl: "+15%",
    breakEven: "58000",
    status: "open",
  },
  {
    id: 12,
    tickerPair: "ETH-EUR",
    exchange: "Binance",
    size: "18",
    market: "3500",
    nominal: "63000",
    pnl: "+10%",
    breakEven: "3200",
    status: "open",
  },
  {
    id: 13,
    tickerPair: "XRP-EUR",
    exchange: "Kraken",
    size: "1100",
    market: "1.2",
    nominal: "1320",
    pnl: "-4%",
    breakEven: "1.3",
    status: "pending",
  },
  {
    id: 14,
    tickerPair: "LTC-EUR",
    exchange: "Gemini",
    size: "45",
    market: "180",
    nominal: "8100",
    pnl: "+2%",
    breakEven: "175",
    status: "closed",
  },
  {
    id: 15,
    tickerPair: "ADA-EUR",
    exchange: "Coinbase",
    size: "450",
    market: "1.8",
    nominal: "810",
    pnl: "+8%",
    breakEven: "1.7",
    status: "open",
  },
  {
    id: 16,
    tickerPair: "DOGE-EUR",
    exchange: "Binance",
    size: "9500",
    market: "0.25",
    nominal: "2375",
    pnl: "+15%",
    breakEven: "0.22",
    status: "open",
  },
  {
    id: 17,
    tickerPair: "DOT-EUR",
    exchange: "Kraken",
    size: "75",
    market: "32",
    nominal: "2400",
    pnl: "+12%",
    breakEven: "28",
    status: "pending",
  },
  {
    id: 18,
    tickerPair: "SOL-EUR",
    exchange: "Gemini",
    size: "55",
    market: "140",
    nominal: "7700",
    pnl: "+3%",
    breakEven: "135",
    status: "closed",
  },
  {
    id: 19,
    tickerPair: "UNI-EUR",
    exchange: "Coinbase",
    size: "90",
    market: "23",
    nominal: "2070",
    pnl: "-2%",
    breakEven: "24",
    status: "open",
  },
  {
    id: 20,
    tickerPair: "LINK-EUR",
    exchange: "Binance",
    size: "190",
    market: "28",
    nominal: "5320",
    pnl: "+10%",
    breakEven: "26",
    status: "open",
  },
  {
    id: 21,
    tickerPair: "BTC-USD",
    exchange: "Coinbase",
    size: "36",
    market: "64000",
    nominal: "2304000",
    pnl: "+10%",
    breakEven: "58000",
    status: "open",
  },
  {
    id: 22,
    tickerPair: "ETH-USD",
    exchange: "Binance",
    size: "20",
    market: "3700",
    nominal: "74000",
    pnl: "+6%",
    breakEven: "3500",
    status: "open",
  },
  {
    id: 23,
    tickerPair: "XRP-USD",
    exchange: "Kraken",
    size: "1300",
    market: "1.4",
    nominal: "1820",
    pnl: "-3%",
    breakEven: "1.5",
    status: "pending",
  },
  {
    id: 24,
    tickerPair: "LTC-USD",
    exchange: "Gemini",
    size: "55",
    market: "210",
    nominal: "11550",
    pnl: "+4%",
    breakEven: "200",
    status: "closed",
  },
  {
    id: 25,
    tickerPair: "ADA-USD",
    exchange: "Coinbase",
    size: "480",
    market: "2.2",
    nominal: "1056",
    pnl: "+9%",
    breakEven: "2",
    status: "open",
  },
  {
    id: 26,
    tickerPair: "DOGE-USD",
    exchange: "Binance",
    size: "10500",
    market: "0.35",
    nominal: "3675",
    pnl: "+18%",
    breakEven: "0.3",
    status: "open",
  },
  {
    id: 27,
    tickerPair: "DOT-USD",
    exchange: "Kraken",
    size: "85",
    market: "40",
    nominal: "3400",
    pnl: "+13%",
    breakEven: "35",
    status: "pending",
  },
  {
    id: 28,
    tickerPair: "SOL-USD",
    exchange: "Gemini",
    size: "65",
    market: "160",
    nominal: "10400",
    pnl: "+6%",
    breakEven: "150",
    status: "closed",
  },
  {
    id: 29,
    tickerPair: "UNI-USD",
    exchange: "Coinbase",
    size: "110",
    market: "28",
    nominal: "3080",
    pnl: "-1%",
    breakEven: "29",
    status: "open",
  },
  {
    id: 30,
    tickerPair: "LINK-USD",
    exchange: "Binance",
    size: "210",
    market: "33",
    nominal: "6930",
    pnl: "+11%",
    breakEven: "30",
    status: "open",
  },
];

export { columns, trades, statusOptions };
